apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - name: frigate
          image: ghcr.io/blakeblackshear/frigate:stable
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /config
              name: frigate-config
      volumes:
        - name: frigate-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  selector:
    app: frigate
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP